### ISSUE TITLE
Tag: (0002, 0010) TransferSyntaxUID - not found in dataset ERROR

### ISSUE THREAD

**Issue by barna21** [RadOncSys/dcmM2S#1]
Hello,
when I try to convert multiframe DICOM to single frame, I receive next error:
Tag: (0002, 0010) not found in dataset

Please can you help me?
I use Fo-Dicom 5.0
![1](https://user-images.githubusercontent.com/33651659/140619696-b6da7766-b8e9-4623-9117-2fff9396aba4.JPG)
.0

**Comment by ggorlachev** [comment]
There is something strange.
Fo-Dicom 5.0 works with Net Core. Upgrade to it assumes changing project type.
In order to exclude possible problem on this way I created and committed new version of project from scratch.
Code itself not changed except update namespaces.
With my files everything works fine.
If problem still exist please check if Tag: (0002, 0010) is present in DICOM files.
This Tag is mandatory and defines the following data format.
If both problem and Tag exist please send me one image file for аurther investigation.

**Comment by barna21** [comment]
Hello,
I sent you by email some DICOM Multiframe samples. Can you please take a look?
Thank you in advance!

**Comment by barna21** [comment]
did you receive?

**Comment by ggorlachev** [comment]
Yes, I received.
Brief look shows those files do not have metadata, i.e. all 0x0002 group is missed.
I recommend [Makhaon DICOM dump](http://www.makhaon.com/index.php?lng=en&p=products&id=dicomdump) program to investigate DIOCM files content.
Some DICOM viewers do not open such files.
Probably it can be corrected throw export software configuration.
I will check if it is possible to extend dcmM2S to manage such files.

**Comment by ggorlachev** [comment]
Added support of files without Meta Information.
This is done through the creating a copy of DicomFile object with Dataset as an argument of the constructor.
